blank_issues_enabled: false
contact_links:
  - name: Question or Need Help?
    url: https://github.com/Abdelrahman-habib/expense-tracker/discussions
    about: Please ask and answer questions in our GitHub Discussions.
  - name: Documentation
    url: https://github.com/Abdelrahman-habib/expense-tracker/docs
    about: Check our documentation for guides and API references.
