name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"

      - name: Install dependencies
        run: go mod download

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: |
          go test ./...
        env:
          GO111MODULE: on
          CGO_ENABLED: 0
          CI: "true" # Ensure tests know they're running in CI
